- hosts: datanode
  vars:
          - node: "data"
  vars_prompt:
          - name: nn_ip
            prompt: "Enter NameNode IP Address"
            private: no
          - name: dir_hadoop
            prompt: "Enter DataNode Directory"
            private: no
  tasks:
  - name: "Copying jdk software"
    copy:
            src: "requirements/softwares/jdk-8u171-linux-x64.rpm"
            dest: "/root/"

  - name: "Copying hadoop software"
    copy:
            src: "requirements/softwares/hadoop-1.2.1-1.x86_64.rpm"
            dest: "/root/"
  
  - name: "Installing jdk software"
    yum:
            name: "/root/jdk-8u171-linux-x64.rpm"
            state: present
            disable_gpg_check: yes
  
  - name: "Installing Hadoop software"
    command: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"

  - name: "Create directory for DataNode"
    file:
            path: "{{ dir_hadoop }}"
            state: directory

  - name: "Configuring hdfs-site.xml file"
    template:
            src: "requirements/hdfsfile.j2"
            dest: "/etc/hadoop/hdfs-site.xml"

  - name: "Configuring core-site.xml file"
    template:
            src: "requirements/corefile.j2"
            dest: "/etc/hadoop/core-site.xml"

  - name: "Clearing some memory"
    shell: "echo 3 > /proc/sys/vm/drop_caches"
 
  - name: "Starting DataNode services"
    command: "hadoop-daemon.sh start datanode"
    ignore_errors: yes
